/* AUTO-GENERATED FILE - do not edit by hand.
 * Generated by gen_serializers.py
 */
#pragma once
#include <stdio.h>
#include <stdint.h>
#include <inttypes.h>
#include <stdbool.h>
#include <string.h>

#include "conversion.h"
#include "log_clcmsw_ipmc_hum.h"


/* ---- forward declarations ---- */
static void print_pcs_hum_board_data_to_the_file(FILE *outfp, const pcs_hum_board_data *var, bool is_sliced);
static void ltobend_pcs_hum_board_data(pcs_hum_board_data *var);
static void print_pcs_hum_board_data_values_to_the_file(FILE *outfp, const pcs_hum_board_data *var, bool is_sliced);
static void print_clcmsw_ipmc_hum_data_to_the_file(FILE *outfp, const clcmsw_ipmc_hum_data *var, bool is_sliced);
static void ltobend_clcmsw_ipmc_hum_data(clcmsw_ipmc_hum_data *var);
static void print_clcmsw_ipmc_hum_data_values_to_the_file(FILE *outfp, const clcmsw_ipmc_hum_data *var, bool is_sliced);

/* ==================== pcs_hum_board_data ==================== */
static void print_pcs_hum_board_data_to_the_file(FILE *outfp, const pcs_hum_board_data *var, bool is_sliced) {
    (void)var;
    bool first = true;
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "mcu_vin_ok");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "mcu_holdup_ok");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "fail_mcu");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "mcu_vin_ok_valid");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "mcu_holdup_ok_valid");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "fail_mcu_valid");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_signed_value_type_to_the_file(outfp, &(var->temp_1), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_signed_value_type_to_the_file(outfp, &(var->temp_2), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_to_the_file(outfp, &(var->inp_v_meas), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_to_the_file(outfp, &(var->holdp_v_meas), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_to_the_file(outfp, &(var->outp_v_meas), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_to_the_file(outfp, &(var->inp_cur_meas), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_to_the_file(outfp, &(var->holdp_cur_meas), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_to_the_file(outfp, &(var->outp_cur_meas), true);
    if (!is_sliced) fprintf(outfp, "\n");
}

static void ltobend_pcs_hum_board_data(pcs_hum_board_data *var) {
    var->mcu_vin_ok = (int)ntohl_local((uint32_t)var->mcu_vin_ok);
    var->mcu_holdup_ok = (int)ntohl_local((uint32_t)var->mcu_holdup_ok);
    var->fail_mcu = (int)ntohl_local((uint32_t)var->fail_mcu);
    var->mcu_vin_ok_valid = (int)ntohl_local((uint32_t)var->mcu_vin_ok_valid);
    var->mcu_holdup_ok_valid = (int)ntohl_local((uint32_t)var->mcu_holdup_ok_valid);
    var->fail_mcu_valid = (int)ntohl_local((uint32_t)var->fail_mcu_valid);
    ltobend_Pcs_ipmc_signed_value_type(&var->temp_1);
    ltobend_Pcs_ipmc_signed_value_type(&var->temp_2);
    ltobend_Pcs_ipmc_unsigned_value_type(&var->inp_v_meas);
    ltobend_Pcs_ipmc_unsigned_value_type(&var->holdp_v_meas);
    ltobend_Pcs_ipmc_unsigned_value_type(&var->outp_v_meas);
    ltobend_Pcs_ipmc_unsigned_value_type(&var->inp_cur_meas);
    ltobend_Pcs_ipmc_unsigned_value_type(&var->holdp_cur_meas);
    ltobend_Pcs_ipmc_unsigned_value_type(&var->outp_cur_meas);
}

static void print_pcs_hum_board_data_values_to_the_file(FILE *outfp, const pcs_hum_board_data *var, bool is_sliced) {
    bool first = true;
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->mcu_vin_ok);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->mcu_holdup_ok);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->fail_mcu);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->mcu_vin_ok_valid);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->mcu_holdup_ok_valid);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->fail_mcu_valid);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_signed_value_type_values_to_the_file(outfp, (const Pcs_ipmc_signed_value_type *)&(var->temp_1), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_signed_value_type_values_to_the_file(outfp, (const Pcs_ipmc_signed_value_type *)&(var->temp_2), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_values_to_the_file(outfp, (const Pcs_ipmc_unsigned_value_type *)&(var->inp_v_meas), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_values_to_the_file(outfp, (const Pcs_ipmc_unsigned_value_type *)&(var->holdp_v_meas), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_values_to_the_file(outfp, (const Pcs_ipmc_unsigned_value_type *)&(var->outp_v_meas), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_values_to_the_file(outfp, (const Pcs_ipmc_unsigned_value_type *)&(var->inp_cur_meas), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_values_to_the_file(outfp, (const Pcs_ipmc_unsigned_value_type *)&(var->holdp_cur_meas), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_values_to_the_file(outfp, (const Pcs_ipmc_unsigned_value_type *)&(var->outp_cur_meas), true);
    if (!is_sliced) fprintf(outfp, "\n");
}

/* ==================== clcmsw_ipmc_hum_data ==================== */
static void print_clcmsw_ipmc_hum_data_to_the_file(FILE *outfp, const clcmsw_ipmc_hum_data *var, bool is_sliced) {
    (void)var;
    bool first = true;
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_clcmsw_generic_ipmc_data_type_to_the_file(outfp, &(var->generic_ipmc), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_pcs_hum_board_data_to_the_file(outfp, &(var->hum_data), true);
    if (!is_sliced) fprintf(outfp, "\n");
}

static void ltobend_clcmsw_ipmc_hum_data(clcmsw_ipmc_hum_data *var) {
    ltobend_clcmsw_generic_ipmc_data_type(&var->generic_ipmc);
    ltobend_pcs_hum_board_data(&var->hum_data);
}

static void print_clcmsw_ipmc_hum_data_values_to_the_file(FILE *outfp, const clcmsw_ipmc_hum_data *var, bool is_sliced) {
    bool first = true;
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_clcmsw_generic_ipmc_data_type_values_to_the_file(outfp, (const clcmsw_generic_ipmc_data_type *)&(var->generic_ipmc), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_pcs_hum_board_data_values_to_the_file(outfp, (const pcs_hum_board_data *)&(var->hum_data), true);
    if (!is_sliced) fprintf(outfp, "\n");
}

/* ================== Top-Level Parsers ================== */
void log_clcmsw_ipmc_hum_pcs_LRM_dev_arr_type_log_header_print(FILE **fp, int print_header) {
   FILE *outfp = *fp;
   if (print_header) fprintf(*fp,  "DEVICE ID,COMPONENT TYPE,LOG MESSAGE TYPE,TIMESTAMP (ns), LOG PAYLOAD LENGTH,");
   static const pcs_LRM_dev_arr_type dummy;
   print_pcs_LRM_dev_arr_type_to_the_file(outfp, &dummy, false);
}

void log_clcmsw_ipmc_hum_pcs_LRM_dev_arr_type_log_parser(FILE *outfp, pcs_LRM_dev_arr_type *s) {
   ltobend_pcs_LRM_dev_arr_type(s);
   print_pcs_LRM_dev_arr_type_values_to_the_file(outfp, s, false);
}

void log_clcmsw_ipmc_hum_pcs_chassis_man_record_table_type_log_header_print(FILE **fp, int print_header) {
   FILE *outfp = *fp;
   if (print_header) fprintf(*fp,  "DEVICE ID,COMPONENT TYPE,LOG MESSAGE TYPE,TIMESTAMP (ns), LOG PAYLOAD LENGTH,");
   static const pcs_chassis_man_record_table_type dummy;
   print_pcs_chassis_man_record_table_type_to_the_file(outfp, &dummy, false);
}

void log_clcmsw_ipmc_hum_pcs_chassis_man_record_table_type_log_parser(FILE *outfp, pcs_chassis_man_record_table_type *s) {
   ltobend_pcs_chassis_man_record_table_type(s);
   print_pcs_chassis_man_record_table_type_values_to_the_file(outfp, s, false);
}

void log_clcmsw_ipmc_hum_Pcs_ipmc_limit_status_log_header_print(FILE **fp, int print_header) {
   FILE *outfp = *fp;
   if (print_header) fprintf(*fp,  "DEVICE ID,COMPONENT TYPE,LOG MESSAGE TYPE,TIMESTAMP (ns), LOG PAYLOAD LENGTH,");
   static const Pcs_ipmc_limit_status dummy;
   print_Pcs_ipmc_limit_status_to_the_file(outfp, &dummy, false);
}

void log_clcmsw_ipmc_hum_Pcs_ipmc_limit_status_log_parser(FILE *outfp, Pcs_ipmc_limit_status *s) {
   ltobend_Pcs_ipmc_limit_status(s);
   print_Pcs_ipmc_limit_status_values_to_the_file(outfp, s, false);
}

void log_clcmsw_ipmc_hum_Pcs_ipmc_signed_value_type_log_header_print(FILE **fp, int print_header) {
   FILE *outfp = *fp;
   if (print_header) fprintf(*fp,  "DEVICE ID,COMPONENT TYPE,LOG MESSAGE TYPE,TIMESTAMP (ns), LOG PAYLOAD LENGTH,");
   static const Pcs_ipmc_signed_value_type dummy;
   print_Pcs_ipmc_signed_value_type_to_the_file(outfp, &dummy, false);
}

void log_clcmsw_ipmc_hum_Pcs_ipmc_signed_value_type_log_parser(FILE *outfp, Pcs_ipmc_signed_value_type *s) {
   ltobend_Pcs_ipmc_signed_value_type(s);
   print_Pcs_ipmc_signed_value_type_values_to_the_file(outfp, s, false);
}

void log_clcmsw_ipmc_hum_Pcs_ipmc_unsigned_value_type_log_header_print(FILE **fp, int print_header) {
   FILE *outfp = *fp;
   if (print_header) fprintf(*fp,  "DEVICE ID,COMPONENT TYPE,LOG MESSAGE TYPE,TIMESTAMP (ns), LOG PAYLOAD LENGTH,");
   static const Pcs_ipmc_unsigned_value_type dummy;
   print_Pcs_ipmc_unsigned_value_type_to_the_file(outfp, &dummy, false);
}

void log_clcmsw_ipmc_hum_Pcs_ipmc_unsigned_value_type_log_parser(FILE *outfp, Pcs_ipmc_unsigned_value_type *s) {
   ltobend_Pcs_ipmc_unsigned_value_type(s);
   print_Pcs_ipmc_unsigned_value_type_values_to_the_file(outfp, s, false);
}

void log_clcmsw_ipmc_hum_clcmsw_generic_ipmc_data_type_log_header_print(FILE **fp, int print_header) {
   FILE *outfp = *fp;
   if (print_header) fprintf(*fp,  "DEVICE ID,COMPONENT TYPE,LOG MESSAGE TYPE,TIMESTAMP (ns), LOG PAYLOAD LENGTH,");
   static const clcmsw_generic_ipmc_data_type dummy;
   print_clcmsw_generic_ipmc_data_type_to_the_file(outfp, &dummy, false);
}

void log_clcmsw_ipmc_hum_clcmsw_generic_ipmc_data_type_log_parser(FILE *outfp, clcmsw_generic_ipmc_data_type *s) {
   ltobend_clcmsw_generic_ipmc_data_type(s);
   print_clcmsw_generic_ipmc_data_type_values_to_the_file(outfp, s, false);
}

void log_clcmsw_ipmc_hum_pcs_hum_board_data_log_header_print(FILE **fp, int print_header) {
   FILE *outfp = *fp;
   if (print_header) fprintf(*fp,  "DEVICE ID,COMPONENT TYPE,LOG MESSAGE TYPE,TIMESTAMP (ns), LOG PAYLOAD LENGTH,");
   static const pcs_hum_board_data dummy;
   print_pcs_hum_board_data_to_the_file(outfp, &dummy, false);
}

void log_clcmsw_ipmc_hum_pcs_hum_board_data_log_parser(FILE *outfp, pcs_hum_board_data *s) {
   ltobend_pcs_hum_board_data(s);
   print_pcs_hum_board_data_values_to_the_file(outfp, s, false);
}

void log_clcmsw_ipmc_hum_clcmsw_ipmc_hum_data_log_header_print(FILE **fp, int print_header) {
   FILE *outfp = *fp;
   if (print_header) fprintf(*fp,  "DEVICE ID,COMPONENT TYPE,LOG MESSAGE TYPE,TIMESTAMP (ns), LOG PAYLOAD LENGTH,");
   static const clcmsw_ipmc_hum_data dummy;
   print_clcmsw_ipmc_hum_data_to_the_file(outfp, &dummy, false);
}

void log_clcmsw_ipmc_hum_clcmsw_ipmc_hum_data_log_parser(FILE *outfp, clcmsw_ipmc_hum_data *s) {
   ltobend_clcmsw_ipmc_hum_data(s);
   print_clcmsw_ipmc_hum_data_values_to_the_file(outfp, s, false);
}

