/* AUTO-GENERATED FILE - do not edit by hand.
 * Generated by gen_serializers.py
 */
#pragma once
#include <stdio.h>
#include <stdint.h>
#include <inttypes.h>
#include <stdbool.h>
#include <string.h>

#include "conversion.h"
#include "log_clcmsw_ipmc_psm.h"


/* ---- forward declarations ---- */
static void print_pcs_psm_board_data_to_the_file(FILE *outfp, const pcs_psm_board_data *var, bool is_sliced);
static void ltobend_pcs_psm_board_data(pcs_psm_board_data *var);
static void print_pcs_psm_board_data_values_to_the_file(FILE *outfp, const pcs_psm_board_data *var, bool is_sliced);
static void print_clcmsw_ipmc_psm_data_to_the_file(FILE *outfp, const clcmsw_ipmc_psm_data *var, bool is_sliced);
static void ltobend_clcmsw_ipmc_psm_data(clcmsw_ipmc_psm_data *var);
static void print_clcmsw_ipmc_psm_data_values_to_the_file(FILE *outfp, const clcmsw_ipmc_psm_data *var, bool is_sliced);


/* ==================== pcs_psm_board_data ==================== */
static void print_pcs_psm_board_data_to_the_file(FILE *outfp, const pcs_psm_board_data *var, bool is_sliced) {
    (void)var;
    bool first = true;
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_signed_value_type_to_the_file(outfp, &(var->tmp175_sensor_1), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_signed_value_type_to_the_file(outfp, &(var->tmp175_sensor_2), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_signed_value_type_to_the_file(outfp, &(var->tmp175_sensor_3), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_signed_value_type_to_the_file(outfp, &(var->tmp175_sensor_4), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_signed_value_type_to_the_file(outfp, &(var->tmp175_sensor_5), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_to_the_file(outfp, &(var->plus_3v3aux_voltage), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_to_the_file(outfp, &(var->plus_5v_voltage), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_to_the_file(outfp, &(var->plus_12v_voltage), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_to_the_file(outfp, &(var->mcotsc27012ft_volt), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_to_the_file(outfp, &(var->inp_vlt), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_to_the_file(outfp, &(var->inp_vlt_n), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_to_the_file(outfp, &(var->plus_3v3aux_current), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_to_the_file(outfp, &(var->plus_5v_current), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_to_the_file(outfp, &(var->plus_12v_current), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_to_the_file(outfp, &(var->inp_cur_p), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_to_the_file(outfp, &(var->inp_cur_n), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "input_cur_alrt");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "plus_3v3_over_cur_alrt");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "plus_5v_over_cur_al");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "plus_12v_over_cur_alrt");
    if (!is_sliced) fprintf(outfp, "\n");
}

static void ltobend_pcs_psm_board_data(pcs_psm_board_data *var) {
    ltobend_Pcs_ipmc_signed_value_type(&var->tmp175_sensor_1);
    ltobend_Pcs_ipmc_signed_value_type(&var->tmp175_sensor_2);
    ltobend_Pcs_ipmc_signed_value_type(&var->tmp175_sensor_3);
    ltobend_Pcs_ipmc_signed_value_type(&var->tmp175_sensor_4);
    ltobend_Pcs_ipmc_signed_value_type(&var->tmp175_sensor_5);
    ltobend_Pcs_ipmc_unsigned_value_type(&var->plus_3v3aux_voltage);
    ltobend_Pcs_ipmc_unsigned_value_type(&var->plus_5v_voltage);
    ltobend_Pcs_ipmc_unsigned_value_type(&var->plus_12v_voltage);
    ltobend_Pcs_ipmc_unsigned_value_type(&var->mcotsc27012ft_volt);
    ltobend_Pcs_ipmc_unsigned_value_type(&var->inp_vlt);
    ltobend_Pcs_ipmc_unsigned_value_type(&var->inp_vlt_n);
    ltobend_Pcs_ipmc_unsigned_value_type(&var->plus_3v3aux_current);
    ltobend_Pcs_ipmc_unsigned_value_type(&var->plus_5v_current);
    ltobend_Pcs_ipmc_unsigned_value_type(&var->plus_12v_current);
    ltobend_Pcs_ipmc_unsigned_value_type(&var->inp_cur_p);
    ltobend_Pcs_ipmc_unsigned_value_type(&var->inp_cur_n);
    var->input_cur_alrt = (int)ntohl_local((uint32_t)var->input_cur_alrt);
    var->plus_3v3_over_cur_alrt = (int)ntohl_local((uint32_t)var->plus_3v3_over_cur_alrt);
    var->plus_5v_over_cur_al = (int)ntohl_local((uint32_t)var->plus_5v_over_cur_al);
    var->plus_12v_over_cur_alrt = (int)ntohl_local((uint32_t)var->plus_12v_over_cur_alrt);
}

static void print_pcs_psm_board_data_values_to_the_file(FILE *outfp, const pcs_psm_board_data *var, bool is_sliced) {
    bool first = true;
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_signed_value_type_values_to_the_file(outfp, (const Pcs_ipmc_signed_value_type *)&(var->tmp175_sensor_1), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_signed_value_type_values_to_the_file(outfp, (const Pcs_ipmc_signed_value_type *)&(var->tmp175_sensor_2), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_signed_value_type_values_to_the_file(outfp, (const Pcs_ipmc_signed_value_type *)&(var->tmp175_sensor_3), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_signed_value_type_values_to_the_file(outfp, (const Pcs_ipmc_signed_value_type *)&(var->tmp175_sensor_4), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_signed_value_type_values_to_the_file(outfp, (const Pcs_ipmc_signed_value_type *)&(var->tmp175_sensor_5), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_values_to_the_file(outfp, (const Pcs_ipmc_unsigned_value_type *)&(var->plus_3v3aux_voltage), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_values_to_the_file(outfp, (const Pcs_ipmc_unsigned_value_type *)&(var->plus_5v_voltage), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_values_to_the_file(outfp, (const Pcs_ipmc_unsigned_value_type *)&(var->plus_12v_voltage), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_values_to_the_file(outfp, (const Pcs_ipmc_unsigned_value_type *)&(var->mcotsc27012ft_volt), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_values_to_the_file(outfp, (const Pcs_ipmc_unsigned_value_type *)&(var->inp_vlt), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_values_to_the_file(outfp, (const Pcs_ipmc_unsigned_value_type *)&(var->inp_vlt_n), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_values_to_the_file(outfp, (const Pcs_ipmc_unsigned_value_type *)&(var->plus_3v3aux_current), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_values_to_the_file(outfp, (const Pcs_ipmc_unsigned_value_type *)&(var->plus_5v_current), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_values_to_the_file(outfp, (const Pcs_ipmc_unsigned_value_type *)&(var->plus_12v_current), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_values_to_the_file(outfp, (const Pcs_ipmc_unsigned_value_type *)&(var->inp_cur_p), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_values_to_the_file(outfp, (const Pcs_ipmc_unsigned_value_type *)&(var->inp_cur_n), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->input_cur_alrt);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->plus_3v3_over_cur_alrt);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->plus_5v_over_cur_al);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->plus_12v_over_cur_alrt);
    if (!is_sliced) fprintf(outfp, "\n");
}

/* ==================== clcmsw_ipmc_psm_data ==================== */
static void print_clcmsw_ipmc_psm_data_to_the_file(FILE *outfp, const clcmsw_ipmc_psm_data *var, bool is_sliced) {
    (void)var;
    bool first = true;
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_clcmsw_generic_ipmc_data_type_to_the_file(outfp, &(var->generic_ipmc), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_pcs_psm_board_data_to_the_file(outfp, &(var->hsm_data), true);
    if (!is_sliced) fprintf(outfp, "\n");
}

static void ltobend_clcmsw_ipmc_psm_data(clcmsw_ipmc_psm_data *var) {
    ltobend_clcmsw_generic_ipmc_data_type(&var->generic_ipmc);
    ltobend_pcs_psm_board_data(&var->hsm_data);
}

static void print_clcmsw_ipmc_psm_data_values_to_the_file(FILE *outfp, const clcmsw_ipmc_psm_data *var, bool is_sliced) {
    bool first = true;
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_clcmsw_generic_ipmc_data_type_values_to_the_file(outfp, (const clcmsw_generic_ipmc_data_type *)&(var->generic_ipmc), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_pcs_psm_board_data_values_to_the_file(outfp, (const pcs_psm_board_data *)&(var->hsm_data), true);
    if (!is_sliced) fprintf(outfp, "\n");
}

/* ================== Top-Level Parsers ================== */
void log_clcmsw_ipmc_psm_pcs_LRM_dev_arr_type_log_header_print(FILE **fp, int print_header) {
   FILE *outfp = *fp;
   if (print_header) fprintf(*fp,  "DEVICE ID,COMPONENT TYPE,LOG MESSAGE TYPE,TIMESTAMP (ns), LOG PAYLOAD LENGTH,");
   static const pcs_LRM_dev_arr_type dummy;
   print_pcs_LRM_dev_arr_type_to_the_file(outfp, &dummy, false);
}

void log_clcmsw_ipmc_psm_pcs_LRM_dev_arr_type_log_parser(FILE *outfp, pcs_LRM_dev_arr_type *s) {
   ltobend_pcs_LRM_dev_arr_type(s);
   print_pcs_LRM_dev_arr_type_values_to_the_file(outfp, s, false);
}

void log_clcmsw_ipmc_psm_pcs_chassis_man_record_table_type_log_header_print(FILE **fp, int print_header) {
   FILE *outfp = *fp;
   if (print_header) fprintf(*fp,  "DEVICE ID,COMPONENT TYPE,LOG MESSAGE TYPE,TIMESTAMP (ns), LOG PAYLOAD LENGTH,");
   static const pcs_chassis_man_record_table_type dummy;
   print_pcs_chassis_man_record_table_type_to_the_file(outfp, &dummy, false);
}

void log_clcmsw_ipmc_psm_pcs_chassis_man_record_table_type_log_parser(FILE *outfp, pcs_chassis_man_record_table_type *s) {
   ltobend_pcs_chassis_man_record_table_type(s);
   print_pcs_chassis_man_record_table_type_values_to_the_file(outfp, s, false);
}

void log_clcmsw_ipmc_psm_Pcs_ipmc_limit_status_log_header_print(FILE **fp, int print_header) {
   FILE *outfp = *fp;
   if (print_header) fprintf(*fp,  "DEVICE ID,COMPONENT TYPE,LOG MESSAGE TYPE,TIMESTAMP (ns), LOG PAYLOAD LENGTH,");
   static const Pcs_ipmc_limit_status dummy;
   print_Pcs_ipmc_limit_status_to_the_file(outfp, &dummy, false);
}

void log_clcmsw_ipmc_psm_Pcs_ipmc_limit_status_log_parser(FILE *outfp, Pcs_ipmc_limit_status *s) {
   ltobend_Pcs_ipmc_limit_status(s);
   print_Pcs_ipmc_limit_status_values_to_the_file(outfp, s, false);
}

void log_clcmsw_ipmc_psm_Pcs_ipmc_signed_value_type_log_header_print(FILE **fp, int print_header) {
   FILE *outfp = *fp;
   if (print_header) fprintf(*fp,  "DEVICE ID,COMPONENT TYPE,LOG MESSAGE TYPE,TIMESTAMP (ns), LOG PAYLOAD LENGTH,");
   static const Pcs_ipmc_signed_value_type dummy;
   print_Pcs_ipmc_signed_value_type_to_the_file(outfp, &dummy, false);
}

void log_clcmsw_ipmc_psm_Pcs_ipmc_signed_value_type_log_parser(FILE *outfp, Pcs_ipmc_signed_value_type *s) {
   ltobend_Pcs_ipmc_signed_value_type(s);
   print_Pcs_ipmc_signed_value_type_values_to_the_file(outfp, s, false);
}

void log_clcmsw_ipmc_psm_Pcs_ipmc_unsigned_value_type_log_header_print(FILE **fp, int print_header) {
   FILE *outfp = *fp;
   if (print_header) fprintf(*fp,  "DEVICE ID,COMPONENT TYPE,LOG MESSAGE TYPE,TIMESTAMP (ns), LOG PAYLOAD LENGTH,");
   static const Pcs_ipmc_unsigned_value_type dummy;
   print_Pcs_ipmc_unsigned_value_type_to_the_file(outfp, &dummy, false);
}

void log_clcmsw_ipmc_psm_Pcs_ipmc_unsigned_value_type_log_parser(FILE *outfp, Pcs_ipmc_unsigned_value_type *s) {
   ltobend_Pcs_ipmc_unsigned_value_type(s);
   print_Pcs_ipmc_unsigned_value_type_values_to_the_file(outfp, s, false);
}

void log_clcmsw_ipmc_psm_clcmsw_generic_ipmc_data_type_log_header_print(FILE **fp, int print_header) {
   FILE *outfp = *fp;
   if (print_header) fprintf(*fp,  "DEVICE ID,COMPONENT TYPE,LOG MESSAGE TYPE,TIMESTAMP (ns), LOG PAYLOAD LENGTH,");
   static const clcmsw_generic_ipmc_data_type dummy;
   print_clcmsw_generic_ipmc_data_type_to_the_file(outfp, &dummy, false);
}

void log_clcmsw_ipmc_psm_clcmsw_generic_ipmc_data_type_log_parser(FILE *outfp, clcmsw_generic_ipmc_data_type *s) {
   ltobend_clcmsw_generic_ipmc_data_type(s);
   print_clcmsw_generic_ipmc_data_type_values_to_the_file(outfp, s, false);
}

void log_clcmsw_ipmc_psm_pcs_psm_board_data_log_header_print(FILE **fp, int print_header) {
   FILE *outfp = *fp;
   if (print_header) fprintf(*fp,  "DEVICE ID,COMPONENT TYPE,LOG MESSAGE TYPE,TIMESTAMP (ns), LOG PAYLOAD LENGTH,");
   static const pcs_psm_board_data dummy;
   print_pcs_psm_board_data_to_the_file(outfp, &dummy, false);
}

void log_clcmsw_ipmc_psm_pcs_psm_board_data_log_parser(FILE *outfp, pcs_psm_board_data *s) {
   ltobend_pcs_psm_board_data(s);
   print_pcs_psm_board_data_values_to_the_file(outfp, s, false);
}

void log_clcmsw_ipmc_psm_clcmsw_ipmc_psm_data_log_header_print(FILE **fp, int print_header) {
   FILE *outfp = *fp;
   if (print_header) fprintf(*fp,  "DEVICE ID,COMPONENT TYPE,LOG MESSAGE TYPE,TIMESTAMP (ns), LOG PAYLOAD LENGTH,");
   static const clcmsw_ipmc_psm_data dummy;
   print_clcmsw_ipmc_psm_data_to_the_file(outfp, &dummy, false);
}

void log_clcmsw_ipmc_psm_clcmsw_ipmc_psm_data_log_parser(FILE *outfp, clcmsw_ipmc_psm_data *s) {
   ltobend_clcmsw_ipmc_psm_data(s);
   print_clcmsw_ipmc_psm_data_values_to_the_file(outfp, s, false);
}

