/* AUTO-GENERATED FILE - do not edit by hand.
 * Generated by gen_serializers.py
 */
#pragma once
#include <stdio.h>
#include <stdint.h>
#include <inttypes.h>
#include <stdbool.h>
#include <string.h>

#include "conversion.h"
#include "log_clcmsw_ipmc_io.h"


/* ---- forward declarations ---- */
static void print_pcs_io_board_data_to_the_file(FILE *outfp, const pcs_io_board_data *var, bool is_sliced);
static void ltobend_pcs_io_board_data(pcs_io_board_data *var);
static void print_pcs_io_board_data_values_to_the_file(FILE *outfp, const pcs_io_board_data *var, bool is_sliced);
static void print_clcmsw_ipmc_io_data_to_the_file(FILE *outfp, const clcmsw_ipmc_io_data *var, bool is_sliced);
static void ltobend_clcmsw_ipmc_io_data(clcmsw_ipmc_io_data *var);
static void print_clcmsw_ipmc_io_data_values_to_the_file(FILE *outfp, const clcmsw_ipmc_io_data *var, bool is_sliced);

/* ==================== pcs_io_board_data ==================== */
static void print_pcs_io_board_data_to_the_file(FILE *outfp, const pcs_io_board_data *var, bool is_sliced) {
    (void)var;
    bool first = true;
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "pg_3v3_main");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "pg_2v5_ethsw");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "pg_1v2_main");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "pg_1v0_ethsw");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "pg_1v8_dvi");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "pg_1v8_dvi_xmc");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "pg_disc");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "pg_3v3_main_valid");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "pg_2v5_ethsw_valid");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "pg_1v2_main_valid");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "pg_1v0_ethsw_valid");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "pg_1v8_dvi_valid");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "pg_1v8_dvi_xmc_valid");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "disc_valid");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_signed_value_type_to_the_file(outfp, &(var->tmp451_sensor), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_to_the_file(outfp, &(var->volsns_3v3), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_to_the_file(outfp, &(var->volsns_2v5), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_to_the_file(outfp, &(var->volsns_1v0), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_to_the_file(outfp, &(var->volsns_1v2), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_to_the_file(outfp, &(var->cursns_3v3), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_to_the_file(outfp, &(var->cursns_2v5), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_to_the_file(outfp, &(var->cursns_12v), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_to_the_file(outfp, &(var->cursns_1v), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_to_the_file(outfp, &(var->cursns_1v2), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_to_the_file(outfp, &(var->cursns_5v), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "mpresent");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "ipmi_a_ready");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "ipmi_b_ready");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "mpresent_valid");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "ipmi_a_ready_valid");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "ipmi_b_ready_valid");
    if (!is_sliced) fprintf(outfp, "\n");
}

static void ltobend_pcs_io_board_data(pcs_io_board_data *var) {
    var->pg_3v3_main = (int)ntohl_local((uint32_t)var->pg_3v3_main);
    var->pg_2v5_ethsw = (int)ntohl_local((uint32_t)var->pg_2v5_ethsw);
    var->pg_1v2_main = (int)ntohl_local((uint32_t)var->pg_1v2_main);
    var->pg_1v0_ethsw = (int)ntohl_local((uint32_t)var->pg_1v0_ethsw);
    var->pg_1v8_dvi = (int)ntohl_local((uint32_t)var->pg_1v8_dvi);
    var->pg_1v8_dvi_xmc = (int)ntohl_local((uint32_t)var->pg_1v8_dvi_xmc);
    var->pg_disc = (int)ntohl_local((uint32_t)var->pg_disc);
    var->pg_3v3_main_valid = (int)ntohl_local((uint32_t)var->pg_3v3_main_valid);
    var->pg_2v5_ethsw_valid = (int)ntohl_local((uint32_t)var->pg_2v5_ethsw_valid);
    var->pg_1v2_main_valid = (int)ntohl_local((uint32_t)var->pg_1v2_main_valid);
    var->pg_1v0_ethsw_valid = (int)ntohl_local((uint32_t)var->pg_1v0_ethsw_valid);
    var->pg_1v8_dvi_valid = (int)ntohl_local((uint32_t)var->pg_1v8_dvi_valid);
    var->pg_1v8_dvi_xmc_valid = (int)ntohl_local((uint32_t)var->pg_1v8_dvi_xmc_valid);
    var->disc_valid = (int)ntohl_local((uint32_t)var->disc_valid);
    ltobend_Pcs_ipmc_signed_value_type(&var->tmp451_sensor);
    ltobend_Pcs_ipmc_unsigned_value_type(&var->volsns_3v3);
    ltobend_Pcs_ipmc_unsigned_value_type(&var->volsns_2v5);
    ltobend_Pcs_ipmc_unsigned_value_type(&var->volsns_1v0);
    ltobend_Pcs_ipmc_unsigned_value_type(&var->volsns_1v2);
    ltobend_Pcs_ipmc_unsigned_value_type(&var->cursns_3v3);
    ltobend_Pcs_ipmc_unsigned_value_type(&var->cursns_2v5);
    ltobend_Pcs_ipmc_unsigned_value_type(&var->cursns_12v);
    ltobend_Pcs_ipmc_unsigned_value_type(&var->cursns_1v);
    ltobend_Pcs_ipmc_unsigned_value_type(&var->cursns_1v2);
    ltobend_Pcs_ipmc_unsigned_value_type(&var->cursns_5v);
    var->mpresent = (int)ntohl_local((uint32_t)var->mpresent);
    var->ipmi_a_ready = (int)ntohl_local((uint32_t)var->ipmi_a_ready);
    var->ipmi_b_ready = (int)ntohl_local((uint32_t)var->ipmi_b_ready);
    var->mpresent_valid = (int)ntohl_local((uint32_t)var->mpresent_valid);
    var->ipmi_a_ready_valid = (int)ntohl_local((uint32_t)var->ipmi_a_ready_valid);
    var->ipmi_b_ready_valid = (int)ntohl_local((uint32_t)var->ipmi_b_ready_valid);
}

static void print_pcs_io_board_data_values_to_the_file(FILE *outfp, const pcs_io_board_data *var, bool is_sliced) {
    bool first = true;
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->pg_3v3_main);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->pg_2v5_ethsw);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->pg_1v2_main);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->pg_1v0_ethsw);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->pg_1v8_dvi);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->pg_1v8_dvi_xmc);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->pg_disc);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->pg_3v3_main_valid);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->pg_2v5_ethsw_valid);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->pg_1v2_main_valid);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->pg_1v0_ethsw_valid);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->pg_1v8_dvi_valid);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->pg_1v8_dvi_xmc_valid);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->disc_valid);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_signed_value_type_values_to_the_file(outfp, (const Pcs_ipmc_signed_value_type *)&(var->tmp451_sensor), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_values_to_the_file(outfp, (const Pcs_ipmc_unsigned_value_type *)&(var->volsns_3v3), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_values_to_the_file(outfp, (const Pcs_ipmc_unsigned_value_type *)&(var->volsns_2v5), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_values_to_the_file(outfp, (const Pcs_ipmc_unsigned_value_type *)&(var->volsns_1v0), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_values_to_the_file(outfp, (const Pcs_ipmc_unsigned_value_type *)&(var->volsns_1v2), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_values_to_the_file(outfp, (const Pcs_ipmc_unsigned_value_type *)&(var->cursns_3v3), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_values_to_the_file(outfp, (const Pcs_ipmc_unsigned_value_type *)&(var->cursns_2v5), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_values_to_the_file(outfp, (const Pcs_ipmc_unsigned_value_type *)&(var->cursns_12v), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_values_to_the_file(outfp, (const Pcs_ipmc_unsigned_value_type *)&(var->cursns_1v), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_values_to_the_file(outfp, (const Pcs_ipmc_unsigned_value_type *)&(var->cursns_1v2), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_unsigned_value_type_values_to_the_file(outfp, (const Pcs_ipmc_unsigned_value_type *)&(var->cursns_5v), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->mpresent);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->ipmi_a_ready);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->ipmi_b_ready);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->mpresent_valid);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->ipmi_a_ready_valid);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->ipmi_b_ready_valid);
    if (!is_sliced) fprintf(outfp, "\n");
}

/* ==================== clcmsw_ipmc_io_data ==================== */
static void print_clcmsw_ipmc_io_data_to_the_file(FILE *outfp, const clcmsw_ipmc_io_data *var, bool is_sliced) {
    (void)var;
    bool first = true;
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_clcmsw_generic_ipmc_data_type_to_the_file(outfp, &(var->generic_ipmc), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_pcs_io_board_data_to_the_file(outfp, &(var->io_data), true);
    if (!is_sliced) fprintf(outfp, "\n");
}

static void ltobend_clcmsw_ipmc_io_data(clcmsw_ipmc_io_data *var) {
    ltobend_clcmsw_generic_ipmc_data_type(&var->generic_ipmc);
    ltobend_pcs_io_board_data(&var->io_data);
}

static void print_clcmsw_ipmc_io_data_values_to_the_file(FILE *outfp, const clcmsw_ipmc_io_data *var, bool is_sliced) {
    bool first = true;
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_clcmsw_generic_ipmc_data_type_values_to_the_file(outfp, (const clcmsw_generic_ipmc_data_type *)&(var->generic_ipmc), true);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_pcs_io_board_data_values_to_the_file(outfp, (const pcs_io_board_data *)&(var->io_data), true);
    if (!is_sliced) fprintf(outfp, "\n");
}

/* ================== Top-Level Parsers ================== */
void log_clcmsw_ipmc_io_pcs_LRM_dev_arr_type_log_header_print(FILE **fp, int print_header) {
   FILE *outfp = *fp;
   if (print_header) fprintf(*fp,  "DEVICE ID,COMPONENT TYPE,LOG MESSAGE TYPE,TIMESTAMP (ns), LOG PAYLOAD LENGTH,");
   static const pcs_LRM_dev_arr_type dummy;
   print_pcs_LRM_dev_arr_type_to_the_file(outfp, &dummy, false);
}

void log_clcmsw_ipmc_io_pcs_LRM_dev_arr_type_log_parser(FILE *outfp, pcs_LRM_dev_arr_type *s) {
   ltobend_pcs_LRM_dev_arr_type(s);
   print_pcs_LRM_dev_arr_type_values_to_the_file(outfp, s, false);
}

void log_clcmsw_ipmc_io_pcs_chassis_man_record_table_type_log_header_print(FILE **fp, int print_header) {
   FILE *outfp = *fp;
   if (print_header) fprintf(*fp,  "DEVICE ID,COMPONENT TYPE,LOG MESSAGE TYPE,TIMESTAMP (ns), LOG PAYLOAD LENGTH,");
   static const pcs_chassis_man_record_table_type dummy;
   print_pcs_chassis_man_record_table_type_to_the_file(outfp, &dummy, false);
}

void log_clcmsw_ipmc_io_pcs_chassis_man_record_table_type_log_parser(FILE *outfp, pcs_chassis_man_record_table_type *s) {
   ltobend_pcs_chassis_man_record_table_type(s);
   print_pcs_chassis_man_record_table_type_values_to_the_file(outfp, s, false);
}

void log_clcmsw_ipmc_io_Pcs_ipmc_limit_status_log_header_print(FILE **fp, int print_header) {
   FILE *outfp = *fp;
   if (print_header) fprintf(*fp,  "DEVICE ID,COMPONENT TYPE,LOG MESSAGE TYPE,TIMESTAMP (ns), LOG PAYLOAD LENGTH,");
   static const Pcs_ipmc_limit_status dummy;
   print_Pcs_ipmc_limit_status_to_the_file(outfp, &dummy, false);
}

void log_clcmsw_ipmc_io_Pcs_ipmc_limit_status_log_parser(FILE *outfp, Pcs_ipmc_limit_status *s) {
   ltobend_Pcs_ipmc_limit_status(s);
   print_Pcs_ipmc_limit_status_values_to_the_file(outfp, s, false);
}

void log_clcmsw_ipmc_io_Pcs_ipmc_signed_value_type_log_header_print(FILE **fp, int print_header) {
   FILE *outfp = *fp;
   if (print_header) fprintf(*fp,  "DEVICE ID,COMPONENT TYPE,LOG MESSAGE TYPE,TIMESTAMP (ns), LOG PAYLOAD LENGTH,");
   static const Pcs_ipmc_signed_value_type dummy;
   print_Pcs_ipmc_signed_value_type_to_the_file(outfp, &dummy, false);
}

void log_clcmsw_ipmc_io_Pcs_ipmc_signed_value_type_log_parser(FILE *outfp, Pcs_ipmc_signed_value_type *s) {
   ltobend_Pcs_ipmc_signed_value_type(s);
   print_Pcs_ipmc_signed_value_type_values_to_the_file(outfp, s, false);
}

void log_clcmsw_ipmc_io_Pcs_ipmc_unsigned_value_type_log_header_print(FILE **fp, int print_header) {
   FILE *outfp = *fp;
   if (print_header) fprintf(*fp,  "DEVICE ID,COMPONENT TYPE,LOG MESSAGE TYPE,TIMESTAMP (ns), LOG PAYLOAD LENGTH,");
   static const Pcs_ipmc_unsigned_value_type dummy;
   print_Pcs_ipmc_unsigned_value_type_to_the_file(outfp, &dummy, false);
}

void log_clcmsw_ipmc_io_Pcs_ipmc_unsigned_value_type_log_parser(FILE *outfp, Pcs_ipmc_unsigned_value_type *s) {
   ltobend_Pcs_ipmc_unsigned_value_type(s);
   print_Pcs_ipmc_unsigned_value_type_values_to_the_file(outfp, s, false);
}

void log_clcmsw_ipmc_io_clcmsw_generic_ipmc_data_type_log_header_print(FILE **fp, int print_header) {
   FILE *outfp = *fp;
   if (print_header) fprintf(*fp,  "DEVICE ID,COMPONENT TYPE,LOG MESSAGE TYPE,TIMESTAMP (ns), LOG PAYLOAD LENGTH,");
   static const clcmsw_generic_ipmc_data_type dummy;
   print_clcmsw_generic_ipmc_data_type_to_the_file(outfp, &dummy, false);
}

void log_clcmsw_ipmc_io_clcmsw_generic_ipmc_data_type_log_parser(FILE *outfp, clcmsw_generic_ipmc_data_type *s) {
   ltobend_clcmsw_generic_ipmc_data_type(s);
   print_clcmsw_generic_ipmc_data_type_values_to_the_file(outfp, s, false);
}

void log_clcmsw_ipmc_io_pcs_io_board_data_log_header_print(FILE **fp, int print_header) {
   FILE *outfp = *fp;
   if (print_header) fprintf(*fp,  "DEVICE ID,COMPONENT TYPE,LOG MESSAGE TYPE,TIMESTAMP (ns), LOG PAYLOAD LENGTH,");
   static const pcs_io_board_data dummy;
   print_pcs_io_board_data_to_the_file(outfp, &dummy, false);
}

void log_clcmsw_ipmc_io_pcs_io_board_data_log_parser(FILE *outfp, pcs_io_board_data *s) {
   ltobend_pcs_io_board_data(s);
   print_pcs_io_board_data_values_to_the_file(outfp, s, false);
}

void log_clcmsw_ipmc_io_clcmsw_ipmc_io_data_log_header_print(FILE **fp, int print_header) {
   FILE *outfp = *fp;
   if (print_header) fprintf(*fp,  "DEVICE ID,COMPONENT TYPE,LOG MESSAGE TYPE,TIMESTAMP (ns), LOG PAYLOAD LENGTH,");
   static const clcmsw_ipmc_io_data dummy;
   print_clcmsw_ipmc_io_data_to_the_file(outfp, &dummy, false);
}

void log_clcmsw_ipmc_io_clcmsw_ipmc_io_data_log_parser(FILE *outfp, clcmsw_ipmc_io_data *s) {
   ltobend_clcmsw_ipmc_io_data(s);
   print_clcmsw_ipmc_io_data_values_to_the_file(outfp, s, false);
}

