/* AUTO-GENERATED FILE - do not edit by hand.
 * Generated by gen_serializers.py
 */
#pragma once
#include <stdio.h>
#include <stdint.h>
#include <inttypes.h>
#include <stdbool.h>
#include <string.h>

#include "conversion.h"

/* ---- forward declarations ---- */
static void print_Pcs_ipmc_limit_status_to_the_file(FILE *outfp, const Pcs_ipmc_limit_status *var, bool is_sliced);
static void ltobend_Pcs_ipmc_limit_status(Pcs_ipmc_limit_status *var);
static void print_Pcs_ipmc_limit_status_values_to_the_file(FILE *outfp, const Pcs_ipmc_limit_status *var, bool is_sliced);
static void print_Pcs_ipmc_signed_value_type_to_the_file(FILE *outfp, const Pcs_ipmc_signed_value_type *var, bool is_sliced);
static void ltobend_Pcs_ipmc_signed_value_type(Pcs_ipmc_signed_value_type *var);
static void print_Pcs_ipmc_signed_value_type_values_to_the_file(FILE *outfp, const Pcs_ipmc_signed_value_type *var, bool is_sliced);
static void print_Pcs_ipmc_unsigned_value_type_to_the_file(FILE *outfp, const Pcs_ipmc_unsigned_value_type *var, bool is_sliced);
static void ltobend_Pcs_ipmc_unsigned_value_type(Pcs_ipmc_unsigned_value_type *var);
static void print_Pcs_ipmc_unsigned_value_type_values_to_the_file(FILE *outfp, const Pcs_ipmc_unsigned_value_type *var, bool is_sliced);
static void print_clcmsw_generic_ipmc_data_type_to_the_file(FILE *outfp, const clcmsw_generic_ipmc_data_type *var, bool is_sliced);
static void ltobend_clcmsw_generic_ipmc_data_type(clcmsw_generic_ipmc_data_type *var);
static void print_clcmsw_generic_ipmc_data_type_values_to_the_file(FILE *outfp, const clcmsw_generic_ipmc_data_type *var, bool is_sliced);


/* ==================== Pcs_ipmc_limit_status ==================== */
static void print_Pcs_ipmc_limit_status_to_the_file(FILE *outfp, const Pcs_ipmc_limit_status *var, bool is_sliced) {
    (void)var;
    bool first = true;
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "is_specified");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "validity_region");
    if (!is_sliced) fprintf(outfp, "\n");
}

static void ltobend_Pcs_ipmc_limit_status(Pcs_ipmc_limit_status *var) {
    var->is_specified = (uint32_t)ntohl_local((uint32_t)var->is_specified);
    var->validity_region = (int)ntohl_local((uint32_t)var->validity_region);
}

static void print_Pcs_ipmc_limit_status_values_to_the_file(FILE *outfp, const Pcs_ipmc_limit_status *var, bool is_sliced) {
    bool first = true;
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%" PRIu32, (uint32_t)(var->is_specified));
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->validity_region);
    if (!is_sliced) fprintf(outfp, "\n");
}

/* ==================== Pcs_ipmc_signed_value_type ==================== */
static void print_Pcs_ipmc_signed_value_type_to_the_file(FILE *outfp, const Pcs_ipmc_signed_value_type *var, bool is_sliced) {
    (void)var;
    bool first = true;
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "value");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_limit_status_to_the_file(outfp, &(var->limit_status), true);
    if (!is_sliced) fprintf(outfp, "\n");
}

static void ltobend_Pcs_ipmc_signed_value_type(Pcs_ipmc_signed_value_type *var) {
    var->value = (uint16_t)ntohs_local((uint16_t)var->value);
    ltobend_Pcs_ipmc_limit_status(&var->limit_status);
}

static void print_Pcs_ipmc_signed_value_type_values_to_the_file(FILE *outfp, const Pcs_ipmc_signed_value_type *var, bool is_sliced) {
    bool first = true;
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%" PRIu16, (uint16_t)(var->value));
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_limit_status_values_to_the_file(outfp, (const Pcs_ipmc_limit_status *)&(var->limit_status), true);
    if (!is_sliced) fprintf(outfp, "\n");
}

/* ==================== Pcs_ipmc_unsigned_value_type ==================== */
static void print_Pcs_ipmc_unsigned_value_type_to_the_file(FILE *outfp, const Pcs_ipmc_unsigned_value_type *var, bool is_sliced) {
    (void)var;
    bool first = true;
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "value");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_limit_status_to_the_file(outfp, &(var->limit_status), true);
    if (!is_sliced) fprintf(outfp, "\n");
}

static void ltobend_Pcs_ipmc_unsigned_value_type(Pcs_ipmc_unsigned_value_type *var) {
    var->value = (uint16_t)ntohs_local((uint16_t)var->value);
    ltobend_Pcs_ipmc_limit_status(&var->limit_status);
}

static void print_Pcs_ipmc_unsigned_value_type_values_to_the_file(FILE *outfp, const Pcs_ipmc_unsigned_value_type *var, bool is_sliced) {
    bool first = true;
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%" PRIu16, (uint16_t)(var->value));
    if (!first) { fprintf(outfp, ","); }
    first = false;
    print_Pcs_ipmc_limit_status_values_to_the_file(outfp, (const Pcs_ipmc_limit_status *)&(var->limit_status), true);
    if (!is_sliced) fprintf(outfp, "\n");
}

/* ==================== clcmsw_generic_ipmc_data_type ==================== */
static void print_clcmsw_generic_ipmc_data_type_to_the_file(FILE *outfp, const clcmsw_generic_ipmc_data_type *var, bool is_sliced) {
    (void)var;
    bool first = true;
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "LRM_dev");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "is_auth");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "ipmb_a");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "ipmb_b");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "fw_version_major");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "fw_version_minor");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "fw_version_patch");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "operation_mode");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "sequence_number");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "power_status");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "reset_counter");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "health_data_refresh_counter");
    if (!is_sliced) fprintf(outfp, "\n");
}

static void ltobend_clcmsw_generic_ipmc_data_type(clcmsw_generic_ipmc_data_type *var) {
    var->LRM_dev = (int)ntohl_local((uint32_t)var->LRM_dev);
    var->ipmb_a = (int)ntohl_local((uint32_t)var->ipmb_a);
    var->ipmb_b = (int)ntohl_local((uint32_t)var->ipmb_b);
    var->operation_mode = (int)ntohl_local((uint32_t)var->operation_mode);
    var->sequence_number = (uint16_t)ntohs_local((uint16_t)var->sequence_number);
    var->power_status = (int)ntohl_local((uint32_t)var->power_status);
}

static void print_clcmsw_generic_ipmc_data_type_values_to_the_file(FILE *outfp, const clcmsw_generic_ipmc_data_type *var, bool is_sliced) {
    bool first = true;
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->LRM_dev);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%" PRIu8, (uint8_t)(var->is_auth));
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->ipmb_a);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->ipmb_b);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%" PRIu8, (uint8_t)(var->fw_version_major));
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%" PRIu8, (uint8_t)(var->fw_version_minor));
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%" PRIu8, (uint8_t)(var->fw_version_patch));
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->operation_mode);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%" PRIu16, (uint16_t)(var->sequence_number));
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->power_status);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%" PRIu8, (uint8_t)(var->reset_counter));
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%" PRIu8, (uint8_t)(var->health_data_refresh_counter));
    if (!is_sliced) fprintf(outfp, "\n");
}

/* ================== Top-Level Parsers ================== */
void log_clcmsw_ipmc_generic_pcs_LRM_dev_arr_type_log_header_print(FILE **fp, int print_header) {
   FILE *outfp = *fp;
   if (print_header) fprintf(*fp,  "DEVICE ID,COMPONENT TYPE,LOG MESSAGE TYPE,TIMESTAMP (ns), LOG PAYLOAD LENGTH,");
   static const pcs_LRM_dev_arr_type dummy;
   print_pcs_LRM_dev_arr_type_to_the_file(outfp, &dummy, false);
}

void log_clcmsw_ipmc_generic_pcs_LRM_dev_arr_type_log_parser(FILE *outfp, pcs_LRM_dev_arr_type *s) {
   ltobend_pcs_LRM_dev_arr_type(s);
   print_pcs_LRM_dev_arr_type_values_to_the_file(outfp, s, false);
}

void log_clcmsw_ipmc_generic_pcs_chassis_man_record_table_type_log_header_print(FILE **fp, int print_header) {
   FILE *outfp = *fp;
   if (print_header) fprintf(*fp,  "DEVICE ID,COMPONENT TYPE,LOG MESSAGE TYPE,TIMESTAMP (ns), LOG PAYLOAD LENGTH,");
   static const pcs_chassis_man_record_table_type dummy;
   print_pcs_chassis_man_record_table_type_to_the_file(outfp, &dummy, false);
}

void log_clcmsw_ipmc_generic_pcs_chassis_man_record_table_type_log_parser(FILE *outfp, pcs_chassis_man_record_table_type *s) {
   ltobend_pcs_chassis_man_record_table_type(s);
   print_pcs_chassis_man_record_table_type_values_to_the_file(outfp, s, false);
}

void log_clcmsw_ipmc_generic_Pcs_ipmc_limit_status_log_header_print(FILE **fp, int print_header) {
   FILE *outfp = *fp;
   if (print_header) fprintf(*fp,  "DEVICE ID,COMPONENT TYPE,LOG MESSAGE TYPE,TIMESTAMP (ns), LOG PAYLOAD LENGTH,");
   static const Pcs_ipmc_limit_status dummy;
   print_Pcs_ipmc_limit_status_to_the_file(outfp, &dummy, false);
}

void log_clcmsw_ipmc_generic_Pcs_ipmc_limit_status_log_parser(FILE *outfp, Pcs_ipmc_limit_status *s) {
   ltobend_Pcs_ipmc_limit_status(s);
   print_Pcs_ipmc_limit_status_values_to_the_file(outfp, s, false);
}

void log_clcmsw_ipmc_generic_Pcs_ipmc_signed_value_type_log_header_print(FILE **fp, int print_header) {
   FILE *outfp = *fp;
   if (print_header) fprintf(*fp,  "DEVICE ID,COMPONENT TYPE,LOG MESSAGE TYPE,TIMESTAMP (ns), LOG PAYLOAD LENGTH,");
   static const Pcs_ipmc_signed_value_type dummy;
   print_Pcs_ipmc_signed_value_type_to_the_file(outfp, &dummy, false);
}

void log_clcmsw_ipmc_generic_Pcs_ipmc_signed_value_type_log_parser(FILE *outfp, Pcs_ipmc_signed_value_type *s) {
   ltobend_Pcs_ipmc_signed_value_type(s);
   print_Pcs_ipmc_signed_value_type_values_to_the_file(outfp, s, false);
}

void log_clcmsw_ipmc_generic_Pcs_ipmc_unsigned_value_type_log_header_print(FILE **fp, int print_header) {
   FILE *outfp = *fp;
   if (print_header) fprintf(*fp,  "DEVICE ID,COMPONENT TYPE,LOG MESSAGE TYPE,TIMESTAMP (ns), LOG PAYLOAD LENGTH,");
   static const Pcs_ipmc_unsigned_value_type dummy;
   print_Pcs_ipmc_unsigned_value_type_to_the_file(outfp, &dummy, false);
}

void log_clcmsw_ipmc_generic_Pcs_ipmc_unsigned_value_type_log_parser(FILE *outfp, Pcs_ipmc_unsigned_value_type *s) {
   ltobend_Pcs_ipmc_unsigned_value_type(s);
   print_Pcs_ipmc_unsigned_value_type_values_to_the_file(outfp, s, false);
}

void log_clcmsw_ipmc_generic_clcmsw_generic_ipmc_data_type_log_header_print(FILE **fp, int print_header) {
   FILE *outfp = *fp;
   if (print_header) fprintf(*fp,  "DEVICE ID,COMPONENT TYPE,LOG MESSAGE TYPE,TIMESTAMP (ns), LOG PAYLOAD LENGTH,");
   static const clcmsw_generic_ipmc_data_type dummy;
   print_clcmsw_generic_ipmc_data_type_to_the_file(outfp, &dummy, false);
}

void log_clcmsw_ipmc_generic_clcmsw_generic_ipmc_data_type_log_parser(FILE *outfp, clcmsw_generic_ipmc_data_type *s) {
   ltobend_clcmsw_generic_ipmc_data_type(s);
   print_clcmsw_generic_ipmc_data_type_values_to_the_file(outfp, s, false);
}

