/* AUTO-GENERATED FILE - do not edit by hand.
 * Generated by gen_serializers.py
 */
#pragma once
#include <stdio.h>
#include <stdint.h>
#include <inttypes.h>
#include <stdbool.h>
#include <string.h>

#include "conversion.h"


/* ---- forward declarations ---- */
static void print_pcs_LRM_dev_arr_type_to_the_file(FILE *outfp, const pcs_LRM_dev_arr_type *var, bool is_sliced);
static void ltobend_pcs_LRM_dev_arr_type(pcs_LRM_dev_arr_type *var);
static void print_pcs_LRM_dev_arr_type_values_to_the_file(FILE *outfp, const pcs_LRM_dev_arr_type *var, bool is_sliced);
static void print_pcs_chassis_man_record_table_type_to_the_file(FILE *outfp, const pcs_chassis_man_record_table_type *var, bool is_sliced);
static void ltobend_pcs_chassis_man_record_table_type(pcs_chassis_man_record_table_type *var);
static void print_pcs_chassis_man_record_table_type_values_to_the_file(FILE *outfp, const pcs_chassis_man_record_table_type *var, bool is_sliced);

/* ==================== pcs_LRM_dev_arr_type ==================== */
static void print_pcs_LRM_dev_arr_type_to_the_file(FILE *outfp, const pcs_LRM_dev_arr_type *var, bool is_sliced) {
    (void)var;
    bool first = true;
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "LRM_dev");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "pcs_LRM_serial_ID");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "pcs_LRM_PCB_revision");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "pcs_LRM_PCB_assembly_ID");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "pcs_LRM_mech_rev");
    if (!is_sliced) fprintf(outfp, "\n");
}

static void ltobend_pcs_LRM_dev_arr_type(pcs_LRM_dev_arr_type *var) {
    var->LRM_dev = (int)ntohl_local((uint32_t)var->LRM_dev);
    for (int i = 0; i < 8; ++i)
        var->pcs_LRM_serial_ID[i] = (uint64_t)ntohll_local((uint64_t)var->pcs_LRM_serial_ID[i]);
    for (int i = 0; i < 9; ++i)
        var->pcs_LRM_bilgem_ID[i] = (uint64_t)ntohll_local((uint64_t)var->pcs_LRM_bilgem_ID[i]);
}

static void print_pcs_LRM_dev_arr_type_values_to_the_file(FILE *outfp, const pcs_LRM_dev_arr_type *var, bool is_sliced) {
    bool first = true;
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->LRM_dev);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%" PRIu64, (uint64_t)(var->pcs_LRM_serial_ID));
    if (!first) { fprintf(outfp, ","); }
    first = false;
    for (int i = 0; i < 8; ++i)
        fprintf(outfp, "%u", (var->pcs_LRM_serial_ID[i]));
    if (!first) { fprintf(outfp, ","); }
    first = false;
    for (int i = 0; i < 9; ++i)
        fprintf(outfp, "%u", (var->pcs_LRM_bilgem_ID[i]));
    if (!is_sliced) fprintf(outfp, "\n");
}

/* ==================== pcs_chassis_man_record_table_type ==================== */
static void print_pcs_chassis_man_record_table_type_to_the_file(FILE *outfp, const pcs_chassis_man_record_table_type *var, bool is_sliced) {
    (void)var;
    bool first = true;
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "chassis_manager_mode");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "LRU_id");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "LRU_parity");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "slot_id");
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%s", "sequence_number");
    for (int _i = 0; _i < 17; _i++) {
        if (!first) { fprintf(outfp, ","); }
        first = false;
        pcs_LRM_dev_arr_type temp = var->LRMs_array[_i];
        print_pcs_LRM_dev_arr_type_to_the_file(outfp, &temp, true);
    }
    if (!is_sliced) fprintf(outfp, "\n");
}

static void ltobend_pcs_chassis_man_record_table_type(pcs_chassis_man_record_table_type *var) {
    var->chassis_manager_mode = (int)ntohl_local((uint32_t)var->chassis_manager_mode);
    var->LRU_parity = (int)ntohl_local((uint32_t)var->LRU_parity);
    var->slot_id = (int)ntohl_local((uint32_t)var->slot_id);
    for (int _i = 0; _i < 17; _i++) {
        ltobend_pcs_LRM_dev_arr_type(&var->LRMs_array[_i]);
    }
}

static void print_pcs_chassis_man_record_table_type_values_to_the_file(FILE *outfp, const pcs_chassis_man_record_table_type *var, bool is_sliced) {
    bool first = true;
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->chassis_manager_mode);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%" PRIu8, (uint8_t)(var->LRU_id));
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->LRU_parity);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%d", (int)var->slot_id);
    if (!first) { fprintf(outfp, ","); }
    first = false;
    fprintf(outfp, "%" PRIu8, (uint8_t)(var->sequence_number));
    for (int _i = 0; _i < 17; _i++) {
        if (!first) { fprintf(outfp, ","); }
        first = false;
        print_pcs_LRM_dev_arr_type_values_to_the_file(outfp, (const pcs_LRM_dev_arr_type *)&(var->LRMs_array)[_i], true);
    }
    if (!is_sliced) fprintf(outfp, "\n");
}

/* ================== Top-Level Parsers ================== */
void log_clcmsw_chmc_pcs_LRM_dev_arr_type_log_header_print(FILE **fp, int print_header) {
   FILE *outfp = *fp;
   if (print_header) fprintf(*fp,  "DEVICE ID,COMPONENT TYPE,LOG MESSAGE TYPE,TIMESTAMP (ns), LOG PAYLOAD LENGTH,");
   static const pcs_LRM_dev_arr_type dummy;
   print_pcs_LRM_dev_arr_type_to_the_file(outfp, &dummy, false);
}

void log_clcmsw_chmc_pcs_LRM_dev_arr_type_log_parser(FILE *outfp, pcs_LRM_dev_arr_type *s) {
   ltobend_pcs_LRM_dev_arr_type(s);
   print_pcs_LRM_dev_arr_type_values_to_the_file(outfp, s, false);
}

void log_clcmsw_chmc_pcs_chassis_man_record_table_type_log_header_print(FILE **fp, int print_header) {
   FILE *outfp = *fp;
   if (print_header) fprintf(*fp,  "DEVICE ID,COMPONENT TYPE,LOG MESSAGE TYPE,TIMESTAMP (ns), LOG PAYLOAD LENGTH,");
   static const pcs_chassis_man_record_table_type dummy;
   print_pcs_chassis_man_record_table_type_to_the_file(outfp, &dummy, false);
}

void log_clcmsw_chmc_pcs_chassis_man_record_table_type_log_parser(FILE *outfp, pcs_chassis_man_record_table_type *s) {
   ltobend_pcs_chassis_man_record_table_type(s);
   print_pcs_chassis_man_record_table_type_values_to_the_file(outfp, s, false);
}

